### ISSUE TITLE
Problem downloading the action

### ISSUE THREAD

**Issue by JFCote** [oasdiff/oasdiff-action#14]
I didn't change anything in my workflow but now receive this weird error:

Download action repository 'oasdiff/oasdiff-action@main' (SHA:d67398257eaf22e1bd9dffb33c53fed2344e7185)
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' for action 'oasdiff/oasdiff-action/check-breaking@main'.

Here is the part that use your github action:

```
      - name: Running OpenAPI Spec diff action
        id: test_breaking_changes
        uses: oasdiff/oasdiff-action/check-breaking@main
        with:
          base: 'openapi.old.yaml'
          revision: 'openapi.yaml'
          fail-on-diff: true
```

Do you know if anything could have change on your side?
