### ISSUE TITLE
Integrate oasdiff action output with github PR

### ISSUE THREAD

**Issue by effoeffi** [oasdiff/oasdiff-action#15]
We would like to integrate the output of GitHub Actions, like breaking-changes, with GitHub PRs.
In case there are breaking-changes, the oasdiff output will appear as part of the PR conversation tab.
This would make it easier for our team to collaborate on breaking-changes.

**Comment by jbergstroem** [comment]
By adding line numbers, position and so on it would be trivial to add a pattern matcher!

**Comment by reuvenharrison** [comment]
This PR adds github actions format to breaking-changes: https://github.com/Tufin/oasdiff/pull/386

**Comment by MatejMijoski** [comment]
Is there currently a way to get the output of the action, so that another action can be used to post a comment on the PR?

**Comment by effoeffi** [comment]
> Is there currently a way to get the output of the action, so that another action can be used to post a comment on the PR?

Currently, this action does not output any data. Could you please share more about your use case? Which actions are you using (breaking/changelog/diff)? What do you plan to do with the data? Which specific data do you need?

**Comment by MatejMijoski** [comment]
I think my use-case is relatively simple, which is to add the entire output of the action (New/Modified/Deleted endpoints) as a comment on the PR.

**Comment by effoeffi** [comment]
> I think my use-case is relatively simple, which is to add the entire output of the action (New/Modified/Deleted endpoints) as a comment on the PR. The action is `oasdiff/oasdiff-action/diff@main`. I do think I've found a way to do this, so if you're open to it, I can make a PR.

Sounds great! How do you plan to implement that? Will it be part of the current diff action, or will you add a new action that gets the output of any action (diff, breaking, or changelog) and adds it as a comment to the PR?

**Comment by tuxmachine** [comment]
Commenting here for posterity, but out use-case is the same as Matej, adding a comment to the PR. The workflow would look something like this:

```yaml
    - name: Running OpenAPI Spec diff action
      id: oasdiff
      uses: oasdiff/oasdiff-action/breaking@main
      with:
        base: api-docs.base.json
        revision: api-docs.json
        fail-on-diff: 'false'

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: bot:oasdiff

    - name: Post oasdiff report
      if: ${{ !startsWith(steps.oasdiff.outputs.breaking, 'No breaking changes') || steps.find-comment.outputs.comment-id }}
      uses: peter-evans/create-or-update-comment@v3
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          <!-- bot:oasdiff -->
          Found these breaking changes on the public API:

          ```
          ${{ steps.oasdiff.outputs.breaking }}
          ```
        edit-mode: replace
```
