### ISSUE TITLE
Breaking action does nothing, when fail-on-diff is set to true.

### ISSUE THREAD

**Issue by Remki** [oasdiff/oasdiff-action#54]
Action is great, annotations are great feature and works well when fail-on-diff is set to false. However when it is set to true, action just fails without adding any addnotation or even returning any log to CI.

I have tested it while base and revision is downloaded from backend, and when base is saved locally in repository. Workaroud is to run action two times, maybe I have something wrong configured, but my configuration is pretty basic.

```
 - name: Running OpenAPI Spec diff action, this one works fine, but doesn't fail plan
        uses: oasdiff/oasdiff-action/breaking@v0.0.19
        with:
          base: sample.yml
          revision: http://pathToSwagger
          fail-on-diff: false 

 - name: Running OpenAPI Spec diff action, this fails plan, but doesn't report any issues to user
        uses: oasdiff/oasdiff-action/breaking@v0.0.19
        with:
          base: sample.yml
          revision: http://pathToSwagger
          fail-on-diff: true
```

<img width="1286" alt="image" src="https://github.com/oasdiff/oasdiff-action/assets/5195660/396cd684-7a78-4380-a4b0-f055bf360e0f">
