### ISSUE TITLE
Failing breaking check doesn't fail pipeline

### ISSUE THREAD

**Issue by nunoo** [oasdiff/oasdiff-action#58]
# Failing breaking check doesn't fail pipeline:

<img width="1691" alt="Screenshot 2024-09-26 at 11 04 45 AM" src="https://github.com/user-attachments/assets/607d74cf-f2b5-43f2-97eb-cff9ff9e3354">

Using a github template:

workflows/integration.yaml:

```

  compatibility-check:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: verify compatibility
        uses: "./.github/template/oasdiff"
```

oasdiff/action.yaml:

```
name: lint
description: "Run lint checks on the codebase"

runs:
  using: "composite"
  steps:
    - name: Check Breaking Changes
      uses: oasdiff/oasdiff-action/breaking@main
      with:
        base: ./dist/swagger-old/portal/openapi.yaml
        revision: ./dist/swagger-new/portal/openapi.yaml
```
